server:
  port: 8760

spring:
  application:
    name: vine-gateway
  cloud:
    gateway:
      routes:
        - id: vineId
          uri: lb://VINE-CLIENT
          predicates:
            - Path=/api/vine-service/**
        - id: userId
          uri: lb://USER-CLIENT
          predicates:
            - Path=/api/auth-service/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
